sonar.projectKey=sa-host
sonar.projectName=Serviced Apartments Host
sonar.projectVersion=1.0

sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

# Optional: exclude node_modules, test files, build
sonar.exclusions=**/node_modules/**, **/*.test.js, **/build/**

# SonarQube server URL and auth token
sonar.host.url=http://149.102.141.32:9005
# sonar.login=sqp_3558cf2f6882376a3b295e43f9ae63d7f418e308
sonar.token=squ_df70a3c9dfe0356ccc137bbc0f13fa4541762bc3
