export enum AmenityCategoriesEnum {
    BATHROOM_AMENITIES = "BATHROOM_AMENITIES",
    GARDEN_AMENITIES = "GARDEN_AMENITIES",
    LIVING_ROOM_AMENITIES = "LIVING_ROOM_AMENITIES",
    DINING_ROOM_AMENITIES = "DINING_ROOM_AMENITIES",
    ACCOMMODATION_UNIT_AMENITIES = "ACCOMMODATION_UNIT_AMENITIES",
}
