export enum MainStepsCompleteTypeEnum {
  PROPERTY_DETAILS_COMPLETE = "PROPERTY_DETAILS_COMPLETE",
  ENTIRE_PROPERTY_DETAILS_COMPLETE = "ENTIRE_PROPERTY_DETAILS_COMPLETE",
  UNIT_DETAILS_COMPLETE = "UNIT_DETAILS_COMPLETE",
  IMAGE_UPLOAD_COMPLETE = "IMAGE_UPLOAD_COMPLETE",
  FINAL_STEP_COMPLETE = "FINAL_STEP_COMPLETE",
}
